### ISSUE TITLE
Bug: Navbar/FAQnav spacing (desktop)

### ISSUE THREAD

**Issue by dotmacro** [okTurtles/groupincome.org#21]
There's a small space between the site navbar and the FAQ navbar, allowing a bit of the FAQs to show through.

![image](https://user-images.githubusercontent.com/13082264/145744642-cc34794b-38d4-4b8f-9a54-cac54c5b11a6.png)

This happens in Firefox 95 and Safari 14.1.2. I could not reproduce in Brave (Chromium).

**Comment by leihla** [comment]
I think this have been fixed. Can you confirm @pieer?

**Comment by pieer** [comment]
Fixed

**Comment by dotmacro** [comment]
This bug is still present on Firefox and Safari.

Firefox 96.0.3: 
![image](https://user-images.githubusercontent.com/13082264/151441051-9579e6f9-f2d2-480a-9c7b-82c575f3583e.png)

Safari 14.1.2: 
![image](https://user-images.githubusercontent.com/13082264/151441077-4addd8de-f9a2-43a3-a4a8-1f30a8becc38.png)
